version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f Dockerfile .
     # deploy the image
     - run: |         
         docker login --username=$zereaburukbus@gmail.com --password=$tattooed439 registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$flashlash/web
         docker push registry.heroku.com/$flashlash/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $flashlash